
name: NPM Publish

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up OCaml
        uses: ocaml/setup-ocaml@v1.1.11
        with:
          ocaml-version: 4.13.0

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Deps
        run: |
          opam install .

      - name: Build
        run: |
          eval $(opam env)
          dune build
          ./test.sh
          ./prepublish.sh

      - uses: JS-DevTools/npm-publish@v1
        with:
          package: ./npm/lichenscript-web/package.json
          token: ${{ secrets.NPM_TOKEN }}
